### PR TITLE
Organize requirement files

### PR DESCRIPTION
**Pull request by percyperez**
@orcasgit/orcas-developers Please review.

### CODE REVIEW

**Comment by brad** [comment]
@percyperez If you merge master into this branch, that should fix the tests and make this branch mergeable.

**Comment by percyperez** [comment]
@brad @grokcode Yeah I rebased against master and fixed the conflict

**Comment by brad** [comment]
@percyperez LGTM I like this way of organizing the requirements better.

**Comment by brad** [comment]
:shipit:

**Comment by grokcode** [comment]
Looks good @percyperez, but don't forget to add yourself to `AUTHORS.rst`

**Comment by percyperez** [comment]
@grokcode `AUTHORS.rst` has been updated :)

**Comment by grokcode** [comment]
@percyperez Oh ha. You're way ahead of me.

**Pull request merged**
